name: scrollable-list-fullscreen-mode
description: scrollable-list-fullscreen-mode.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  photo_view: ^0.14.0 #Photo Zoom-in Zoom out gallery feature

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

